version = 0.1

[default.deploy.parameters]
stack_name = "fold-api-2"
resolve_s3 = true
s3_prefix = "fold-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExistingUserPoolId=\"us-east-1_09qgNGF6c\" ExistingUserPoolClientId=\"64v5hjuq65698ukkl0iidjrlbo\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
